---
title: "Assignment 1: Introduction"
author: "Karina Leung"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project"


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have never used Git before, this is my first time. Regarding data analytics and R, my first exposure was when I took ENV 710 with Betsy Albright in the Fall 2021 semester. Before that, I had no experience with R, and I can't say I retained as much helpful information after the class. I did also look up some LinkedIn Learning videos to understand the R language better and tidying data since that was a really confusing part of ENV 710. 

2. Are there any components of the course about which you feel confident?

> Answer: I think I feel confident in the easier parts of R (knitting, starting a new project, and some of the VERY basic commands). For example, I think I could work my way around the mean(), sum(), etc. functions, but integrating different commands with a function is a little far off to me. When we learned "how to code" in ENV 710, it was mostly "here's the code and kind of how it works, now copy & paste & modify to fit your projects." 

3. Are there any components of the course about which you feel apprehensive?

> Answer: The more complicated parts of coding and making sure I understand how the R language works so I can write codes without feeling like I need my hand to be held. Another component I'm apprehensive about is also "relearning" how R works. I had to learn it one way in ENV 710 and it felt like I jumped into the deep end on it, but since we're going back to basics and learning from the beginning, I may have to rewire what information I thought I knew and replace it with information taught in this course, which may get my wires crossed. I also have no confidence in customizing my own graphs or cleaning data (even though I had to watch LinkedIn Learning videos for it).


## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/Karina-Taragittigul/EDA-Spring2023.git ; as a side note: my last name listed on the GitHub account is different from my last name at Duke. But Karina Leung and Karina Taragittigul are both me. Sorry in advance for any confusion around that.

## 4) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
